app/scoring/models.py
from app import db


# Robot score behavior and calculation
class RobotScore(db.Model):
    __tablename__ = 'robot_scores'

    id = db.Column(db.Integer, primary_key=True)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    round_number = db.Column(db.Integer)

    # M04 yellow/ blue bars
    bars_in_west_transfer = db.Column(db.Integer)
    bars_never_in_west_transfer = db.Column(db.Integer)

    # M04 black bars
    black_bars_in_original_position = db.Column(db.Integer)
    black_bars_in_green_or_landfill = db.Column(db.Integer)
    black_bars_elsewhere = db.Column(db.Integer)

    # M02 Methane
    methane_in_truck_or_factory = db.Column(db.Integer)

    # M03 Transport
    truck_supports_yellow_bin = db.Column(db.Boolean)
    yellow_bin_east_of_guide = db.Column(db.Boolean)

    # M05 Careers
    anyone_in_sorter_area = db.Column(db.Boolean)

    # M06 Scrap Cars
    engine_installed = db.Column(db.Boolean)
    car_folded_in_east_transfer = db.Column(db.Boolean)
    car_never_in_safety = db.Column(db.Boolean)

    # M08 Composting
    compost_ejected_not_in_safety = db.Column(db.Boolean)
    compost_ejected_in_safety = db.Column(db.Boolean)

    # M07 Cleanup
    plastic_bags_in_safety = db.Column(db.Integer)
    animals_in_circles_without_bags = db.Column(db.Integer)
    chicken_in_small_landfill_circle = db.Column(db.Boolean)

    # M10 Demolition
    all_beams_not_in_setup_position = db.Column(db.Boolean)

    # M01 Recycled Material
    green_bins_in_opp_safety = db.Column(db.Integer)
    opp_green_bins_in_safety = db.Column(db.Integer)

    # M09 Salvage
    valuables_in_safety = db.Column(db.Boolean)

    # M11 Purchasing Decisions
    planes_in_safety = db.Column(db.Integer)

    # M12 Repurposing
    compost_in_toy_package = db.Column(db.Boolean)
    package_in_original_condition = db.Column(db.Boolean)

    def __init__(self,
                 team=0,
                 round_number=1,
                 # M04 yellow/ blue bars
                 bars_in_west_transfer=0,
                 bars_never_in_west_transfer=0,

                 # M04 black bars
                 black_bars_in_original_position=12,
                 black_bars_in_green_or_landfill=0,
                 black_bars_elsewhere=0,

                 # M02 Methane
                 methane_in_truck_or_factory=0,

                 # M03 Transport
                 truck_supports_yellow_bin=False,
                 yellow_bin_east_of_guide=False,

                 # M05 Careers
                 anyone_in_sorter_area=False,

                 # M06 Scrap Cars
                 engine_installed=False,
                 car_folded_in_east_transfer=False,
                 car_never_in_safety=False,

                 # M08 Composting
                 compost_ejected_not_in_safety=False,
                 compost_ejected_in_safety=False,

                 # M07 Cleanup
                 plastic_bags_in_safety=0,
                 animals_in_circles_without_bags=0,
                 chicken_in_small_landfill_circle=False,

                 # M10 Demolition
                 all_beams_not_in_setup_position=False,

                 # M01 Recycled Material
                 green_bins_in_opp_safety=0,
                 opp_green_bins_in_safety=0,

                 # M09 Salvage
                 valuables_in_safety=False,

                 # M11 Purchasing Decisions
                 planes_in_safety=0,

                 # M12 Repurposing
                 compost_in_toy_package=False,
                 package_in_original_condition=False):
        self.team_id = team
        self.round_number = round_number

        # M04 yellow/ blue bars
        self.bars_in_west_transfer = bars_in_west_transfer
        self.bars_never_in_west_transfer = bars_never_in_west_transfer

        # M04 black bars
        self.black_bars_in_original_position = black_bars_in_original_position
        self.black_bars_in_green_or_landfill = black_bars_in_green_or_landfill
        self.black_bars_elsewhere = black_bars_elsewhere

        # M02 Methane
        self.methane_in_truck_or_factory = methane_in_truck_or_factory

        # M03 Transport
        self.truck_supports_yellow_bin = truck_supports_yellow_bin
        self.yellow_bin_east_of_guide = yellow_bin_east_of_guide

        # M05 Careers
        self.anyone_in_sorter_area = anyone_in_sorter_area

        # M06 Scrap Cars
        self.engine_installed = engine_installed
        self.car_folded_in_east_transfer = car_folded_in_east_transfer
        self.car_never_in_safety = car_never_in_safety

        # M08 Composting
        self.compost_ejected_not_in_safety = compost_ejected_not_in_safety
        self.compost_ejected_in_safety = compost_ejected_in_safety

        # M07 Cleanup
        self.plastic_bags_in_safety = plastic_bags_in_safety
        self.animals_in_circles_without_bags = animals_in_circles_without_bags
        self.chicken_in_small_landfill_circle = chicken_in_small_landfill_circle

        # M10 Demolition
        self.all_beams_not_in_setup_position = all_beams_not_in_setup_position

        # M01 Recycled Material
        self.green_bins_in_opp_safety = green_bins_in_opp_safety
        self.opp_green_bins_in_safety = opp_green_bins_in_safety

        # M09 Salvage
        self.valuables_in_safety = valuables_in_safety

        # M11 Purchasing Decisions
        self.planes_in_safety = planes_in_safety

        # M12 Repurposing
        self.compost_in_toy_package = compost_in_toy_package
        self.package_in_original_condition = package_in_original_condition

    # TODO need unit testing for this
    @property
    def total(self):
        score = 0

        # M01 Recycling
        score += (self.green_bins_in_opp_safety + self.opp_green_bins_in_safety) * 60

        # M02 Methane
        score += self.methane_in_truck_or_factory * 40

        # M03 Transport
        score += 50 if self.truck_supports_yellow_bin else 0
        score += 60 if self.yellow_bin_east_of_guide else 0

        # M04 Sorting (Yellow/ Blue bars)
        score += self.bars_in_west_transfer * 7
        score += self.bars_never_in_west_transfer * 6

        # M04 Sorting (Black Bars)
        score += self.black_bars_in_original_position * 8
        score += self.black_bars_in_green_or_landfill * 3
        score -= self.black_bars_elsewhere * 8

        # M05 Careers
        score += 60 if self.anyone_in_sorter_area else 0

        # M06 Scrap Cars
        if self.car_never_in_safety:
            if self.car_folded_in_east_transfer and not self.engine_installed:
                score += 50
            elif self.engine_installed and not self.car_folded_in_east_transfer:
                score += 65

        # M07 Cleanup
        score += self.plastic_bags_in_safety * 30
        score += self.animals_in_circles_without_bags * 20
        score += 35 if self.chicken_in_small_landfill_circle else 0

        # M08 Composting
        score += 60 if self.compost_ejected_not_in_safety and not self.compost_ejected_in_safety else 0
        score += 80 if self.compost_ejected_in_safety and not self.compost_ejected_not_in_safety else 0

        # M09 Salvage
        score += 60 if self.valuables_in_safety else 0

        # M10 Demolition
        score += 85 if self.all_beams_not_in_setup_position else 0

        # M11 Purchasing Decisions
        score += self.planes_in_safety * 40

        # M12 Repurposing
        score += 40 if self.compost_in_toy_package and self.package_in_original_condition else 0

        return score if score > 0 else 0

app/scoring/views.py
from flask import Blueprint, render_template, request, flash, redirect, \
    url_for, jsonify
from flask.ext.login import login_required
from app import db
from app.util import create_pdf, sortTeamsWithPlaceholder
from app.teams.models import Team
from forms import ScoreForm
from models import RobotScore
from app.models import EventSettings

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_scoring = Blueprint('scoring', __name__, url_prefix='/scores')


@mod_scoring.route("/")
@login_required
def index():
    teams = Team.query.all()
    return render_template("scoring/score_list.html",
                           teams=sorted(teams, key=by_team))


# Ranks rerport in PDF
@mod_scoring.route('/ranks.pdf')
def ranks_pdf():
    teams = Team.query.all()
    
    title = EventSettings.query.first().name
    ranked_teams = sorted(teams, key=by_team_best, reverse=True)
    for i, team in enumerate(ranked_teams):
        team.rank = i + 1

    ranks = render_template("scoring/ranks.html",
                            teams=ranked_teams,
                            title="Ranking Report: %s" % title)
    
    pdf = create_pdf(ranks, 'ranks.pdf')
    return pdf


# API endpoint providing rank data for the pit display
@mod_scoring.route("/api")
def api():
    # Get and sort the teams by rank
    teams = Team.query.all()
    ranked_teams = sorted(teams, key=by_team_best, reverse=True)

    # build the JSON data
    data = []
    for i, team in enumerate(ranked_teams):
        data.append({
            "number": team.number,
            "name": team.name,
            "affiliation": team.affiliation,
            "round1": team.round1.total if team.round1 is not None else "",
            "round2": team.round2.total if team.round2 is not None else "",
            "round3": team.round3.total if team.round3 is not None else "",
            "bestScore": team.best.total if team.best is not None else "",
            "rank": i + 1
        })

    return jsonify(ranks=data)


# Add a new robot score
@mod_scoring.route("/add", methods=['GET', 'POST'])
@login_required
def add():
    teams = Team.query.all()

    if not teams:
        return render_template("no_teams.html")

    form = ScoreForm()

    form.team_id.choices = [(t.id, t.number) for t in
                            sortTeamsWithPlaceholder(teams)]

    # don't allow playoff round options during qualifying, or qualifying during playoffs
    if any(team.highest_round_reached > 3 for team in teams):
        form.round_number.choices = [(-1, 'Select'), (1, '1'), (2, '2'), (3, '3'), (4, 'Quarterfinals'), (5, 'Semifinals'), (6, 'Finals')]
    else:
        form.round_number.choices = [(-1, 'Select'), (1, '1'), (2, '2'), (3, '3')]

    # Gather and preset the team ID and round number fields if provided in URL
    preselected_team = request.args.get('team_id', default=None, type=int)
    preselected_round = request.args.get('round', default=None, type=int)
    if preselected_team is not None and request.method == 'GET':
        form.team_id.data = preselected_team

    if preselected_round is not None and request.method == 'GET':
        form.round_number.data = preselected_round

    repeat = request.args.get('repeat', default=False, type=bool)

    if request.method == 'POST' and request.form['end'] == 'reset':
        return redirect(url_for(".add", round = preselected_round, repeat = True))
    elif request.method == 'POST' and request.form['end'] == 'submit' and form.validate_on_submit():
        score = RobotScore(team=form.team_id.data,
                           round_number=form.round_number.data)
        populate_score(score, form)
        db.session.add(score)
        db.session.commit()
        if repeat:
            flash('Added score for %s round %s' % (score.team.number, score.round_number), 'success')
            return redirect(url_for(".add", round = preselected_round, repeat = True))
        else:
            if form.round_number.data <= 3:
                return redirect(url_for("review"))
            else:
                return redirect(url_for(".playoffs"))
    elif request.method == 'POST':
        flash('Failed validation', 'danger alert-auto-dismiss')
    return render_template("scoring/score_form.html",
                           form=form,
                           id=None,
                           repeat=repeat)


# Edit a previously-entered score
@mod_scoring.route("/<int:score_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(score_id):
    score = RobotScore.query.get(score_id)
    form = ScoreForm(obj=score)
    del form.team_id
    del form.round_number

    if request.method == 'POST' and form.validate_on_submit():
        populate_score(score, form)
        db.session.commit()
        if score.round_number <= 3:
            return redirect(url_for("review"))
        else:
            return redirect(url_for(".playoffs"))
    elif request.method == 'POST':
        flash('Failed validation', 'danger alert-auto-dismiss')
    return render_template("scoring/score_form.html",
                           form=form,
                           team_id=score.team.number,
                           round_number=score.round_number,
                           id=score.id)


# Delete a score
@mod_scoring.route("/<int:score_id>/delete", methods=['GET', 'POST'])
@login_required
def delete(score_id):
    score = RobotScore.query.get(score_id)
    if request.method == 'POST':
        db.session.delete(score)
        db.session.commit()
        if score.round_number <= 3:
            return redirect(url_for("review"))
        else:
            return redirect(url_for(".playoffs"))
    return render_template("delete.html",
                           identifier="%s score for team %d" % (get_round_name(score.round_number), score.team.number))


# Playoffs page
@mod_scoring.route("/playoffs", methods=['GET'])
@login_required
def playoffs():
    teams = Team.query.all()
    if not teams:
        return render_template("no_teams.html")

    quarterfinal_teams = Team.query.filter(Team.highest_round_reached >= 4)
    semifinal_teams = Team.query.filter(Team.highest_round_reached >= 5)
    final_teams = Team.query.filter(Team.highest_round_reached >= 6)
    return render_template("scoring/playoffs.html", quarterfinal_teams=quarterfinal_teams,
                           semifinal_teams=semifinal_teams, final_teams=final_teams)


@mod_scoring.route("/playoffs/<int:selected_round>/populate", methods=['GET', 'POST'])
@login_required
def populate(selected_round):
    if request.method == 'POST':
        event_settings = EventSettings.query.first()

        if selected_round == 4:
            top_teams = sorted(Team.query.all(), key=by_team_best, reverse=True)[
                        :event_settings.quarter_finals_teams]
            for team in top_teams:
                team.highest_round_reached = 4
            db.session.commit()
        elif selected_round == 5:
            top_teams = sorted(Team.query.filter(Team.highest_round_reached >= 4), key=by_quarterfinal, reverse=True)[
                        :event_settings.semi_finals_teams]
            for team in top_teams:
                team.highest_round_reached = 5
            db.session.commit()
        elif selected_round == 6:
            top_teams = sorted(Team.query.filter(Team.highest_round_reached >= 5), key=by_semifinal, reverse=True)[
                        :event_settings.finals_teams]
            for team in top_teams:
                team.highest_round_reached = 6
            db.session.commit()
        return redirect(url_for(".playoffs"))
    else:
        # Check if all data has been entered for previous rounds
        previous_round = 0
        incomplete_data = None
        if selected_round == 4:
            previous_round = "qualifying"
            teams = Team.query.all()
            if any(len(team.qualifying_scores) != 3 for team in teams):
                incomplete_data = True
        elif selected_round == 5:
            previous_round = get_round_name(4)
            if any(team.quarterfinal is None for team in Team.query.filter(Team.highest_round_reached == 4)):
                incomplete_data = True
        elif selected_round == 6:
            previous_round = get_round_name(5)
            if any(team.semifinal is None for team in Team.query.filter(Team.highest_round_reached == 5)):
                incomplete_data = True

        return render_template("scoring/populate_playoffs.html",
                               round=get_round_name(selected_round),
                               previous_round=previous_round,
                               incomplete_data=incomplete_data)


@mod_scoring.route("/playoffs/<int:selected_round>/clear", methods=['GET', 'POST'])
@login_required
def clear_round(selected_round):
    if request.method == 'POST':
        # clear all scores for this round and any future round
        scores = RobotScore.query.filter(RobotScore.round_number >= selected_round)
        for score in scores:
            db.session.delete(score)

        # reset 'highest round reached' field for teams in this round or future rounds
        teams = Team.query.filter(Team.highest_round_reached >= selected_round)
        for team in teams:
            if team.highest_round_reached == 4:
                team.highest_round_reached = 0
            else:
                team.highest_round_reached = selected_round - 1
        db.session.commit()
        return redirect(url_for(".playoffs"))
    return render_template("scoring/clear_round.html", identifier=get_round_name(selected_round))


# Utility method to get live score when score form is being filled out
@mod_scoring.route('/_add_numbers')
def add_numbers():
    score = RobotScore(team=0,
                       round_number=0,

                       # M04 yellow/ blue bars
                       bars_in_west_transfer=request.args.get('bars_in_west_transfer', 0, type=int),

app/templates/scoring/_scoring_helpers.html
{# Render a score with a delete button for a given team and round. Will show 'Add' link if score doesn't exist #}
{% macro render_score(team, round_number) %}
    {% set score = team.get_score_for_round(round_number) %}
    {% if score != None %}
        <a href="{{ url_for('scoring.edit', score_id=score.id) }}">{{ score.total }} </a>
    {% else %}
        <a href="{{ url_for('scoring.add', team_id=team.id, round=round_number) }}"><i>add</i></a>
    {% endif %}
{%- endmacro %}

{# Render a table containing teams and scores for a given playoff round #}
{% macro render_playoff_round(round_name, round_number, teams) %}
    <div class="col-md-4">
        <h2 style="text-align: center;">{{ round_name }}</h2>
        <p style="text-align: center;">
            {% if teams.count() == 0 %}
                <a href="{{ url_for('scoring.populate', selected_round=round_number) }}">Populate</a>
            {% else %}
                <a href="{{ url_for('scoring.clear_round', selected_round=round_number) }}">Clear</a>
            {% endif %}
        </p>
        <table class="table table-hover display" width="100%">
            <thead>
                <tr>
                    <th>Number</th>
                    <th>Name</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                {% for team in teams %}
                    <tr>
                        <td>{{ team.number }}</td>
                        <td>{{ team.name }}</td>
                        <td>{{ render_score(team, round_number) }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{%- endmacro %}

app/templates/scoring/clear_round.html
{% extends "layout.html" %}
{% block title %}Clear Round{% endblock %}
{% block pageContent %}
<script type="text/javascript">
  // TODO Move this to a global JS file
  function goBack() {
    window.history.back();
  }
</script>
  <!--TODO merge with other confirmation page templates?-->
  <!--TODO include future rounds in warning?-->
  <p>Really clear teams and scores for {{ identifier }}?<p>
  <form action="" method="post">
    <p><button class="btn" onclick="goBack()">Cancel</button>  <input type="submit" class="btn btn-danger" value="Clear"></p>
  </form>
{% endblock %}

app/templates/scoring/playoffs.html
{% extends "layout.html" %}
{% import "scoring/_scoring_helpers.html" as macros %}
{% block title %}FLL Playoffs{% endblock %}
{% block pageContent %}
    <h3>Playoffs</h3>
    {{ macros.render_playoff_round("Quarterfinals", 4, quarterfinal_teams) }}
    {{ macros.render_playoff_round("Semifinals", 5, semifinal_teams) }}
    {{ macros.render_playoff_round("Finals", 6, final_teams) }}
{% endblock %}

app/templates/scoring/populate_playoffs.html
{% extends "layout.html" %}
{% block title %}Populate Playoffs{% endblock %}
{% block pageContent %}
<script type="text/javascript">
  // TODO Move this to a global JS file
  function goBack() {
    window.history.back();
  }
</script>
    <p>
        {% if incomplete_data %}
            Not all {{ previous_round }} scores have been entered yet!</p>
        {% endif %}
        Once populated, changes to scores for previous rounds will have no effect on this round.
    </p>
    <p>Really populate teams for {{ round }}?</p>
    <form action="" method="post">
        <p><button class="btn" onclick="goBack()">Cancel</button>  <input type="submit" class="btn btn-primary" value="Populate"></p>
    </form>
{% endblock %}

app/templates/scoring/ranks.html
{% extends "report_base.html" %}
{% block reportContent %}
    <table repeat="1">
    <thead>
        <tr>
            <th>Rank</th>
            <th>Team #</th>
            <th>Name</th>
            <th>Best</th>
            <th>Round 1</th>
            <th>Round 2</th>
            <th>Round 3</th>
        </tr>
    </thead>
    <tbody>
        {% for team in teams %}
            <tr>
                <td>{{ team.rank }}</td>
                <td>{{ team.number }}</td>
                <td>{{ team.name }}</td>
                {% if team.best != None %}
                    <td>{{ team.best.total }}</td>
                {% else %}
                    <td></td>
                {% endif %}

                {% if team.round1 != None %}
                    <td>{{ team.round1.total }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if team.round2 != None %}
                    <td>{{ team.round2.total }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if team.round3 != None %}
                    <td>{{ team.round3.total }}</td>
                {% else %}
                    <td></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

app/templates/scoring/score_form.html
{% extends "form_layout.html" %}
{% import "_helpers.html" as macros %}
{% block title %}FLL Score Form{% endblock %}
{% block pageContent %}
    <script type="text/javascript">
        $( document ).ready(function() {
            updateTotal();
            $("#scrollingForm").css('height', $(window).height()-220);
        });

        // TODO move this to score-specific JS file
        $(function() {
            $('.scoreForm').change(function() {
                console.log("form changed");
                updateTotal();
            });
        });

        function updateTotal() {
            $.getJSON('/scores/_add_numbers', {
                //$("#cargo_plane_location").val()
                bars_in_west_transfer : $("#bars_in_west_transfer").val(),
                bars_never_in_west_transfer : $("#bars_never_in_west_transfer").val(),
                black_bars_in_original_position : $("#black_bars_in_original_position").val(),
                black_bars_in_green_or_landfill : $("#black_bars_in_green_or_landfill").val(),
                black_bars_elsewhere : $("#black_bars_elsewhere").val(),

                methane_in_truck_or_factory : $("#methane_in_truck_or_factory").val(),

                truck_supports_yellow_bin : $("#truck_supports_yellow_bin").val(),
                yellow_bin_east_of_guide : $("#yellow_bin_east_of_guide").val(),

                anyone_in_sorter_area : $("#anyone_in_sorter_area").val(),

                engine_installed : $("#engine_installed").val(),
                car_folded_in_east_transfer : $("#car_folded_in_east_transfer").val(),
                car_never_in_safety : $("#car_never_in_safety").val(),

                compost_ejected_not_in_safety : $("#compost_ejected_not_in_safety").val(),
                compost_ejected_in_safety : $("#compost_ejected_in_safety").val(),

                plastic_bags_in_safety : $("#plastic_bags_in_safety").val(),
                animals_in_circles_without_bags : $("#animals_in_circles_without_bags").val(),
                chicken_in_small_landfill_circle : $("#chicken_in_small_landfill_circle").val(),

                all_beams_not_in_setup_position : $("#all_beams_not_in_setup_position").val(),

                green_bins_in_opp_safety : $("#green_bins_in_opp_safety").val(),
                opp_green_bins_in_safety : $("#opp_green_bins_in_safety").val(),

                valuables_in_safety : $("#valuables_in_safety").val(),

                planes_in_safety : $("#planes_in_safety").val(),

                compost_in_toy_package : $("#compost_in_toy_package").val(),
                package_in_original_condition : $("#package_in_original_condition").val()
            }, function(data) {
                $("#result").text(data.result);
            });
            return false;
        }
    </script>
    {% call macros.render_form(form, class_="scoreForm", include_submit=false) %}
        <div class="row">
            <div class="col-sm-4">
                {% if team_id and round_number %}
                    <div class="form-group">
                        <label class="col-sm-6 control-label">Team</label>
                        <div class="col-sm-6">
                            <p class="form-control-static">{{ team_id }}</p>
                        </div>
                    </div>
                {% else %}
                    {{ macros.render_selector(form.team_id, label_size=6, selector_size=6) }}
                {% endif %}
            </div>
            <div class="col-sm-4">
                {% if team_id and round_number %}
                    <div class="form-group">
                        <label class="col-sm-6 control-label">Round</label>
                        <div class="col-sm-6">
                            <p class="form-control-static">{{ round_number }}</p>
                        </div>
                    </div>
                {% else %}
                    {{ macros.render_selector(form.round_number, label_size=6, selector_size=6) }}
                {% endif %}
            </div>
            <div class="col-sm-4">
                <h4 align="center">Total: <span id="result">0</span></h4>
            </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
              <div class="col-md-12">
                  {{ macros.render_fields("M04: Sorting (Yellow/ Blue bars in matching Green Bins)",
                                      form.bars_in_west_transfer,
                                      form.bars_never_in_west_transfer) }}

                  {{ macros.render_fields("M04: Sorting (Black Bars in matching Green Bin)",
                                          form.black_bars_in_original_position,
                                          form.black_bars_in_green_or_landfill,
                                          form.black_bars_elsewhere) }}

                  {{ macros.render_fields("M02: Methane", form.methane_in_truck_or_factory) }}

                  {{ macros.render_fields("M03: Transport",
                                          form.truck_supports_yellow_bin,
                                          form.yellow_bin_east_of_guide) }}

                  {{ macros.render_fields("M05: Careers", form.anyone_in_sorter_area) }}
                  {{ macros.render_fields("M06: Scrap Cars",
                                          form.engine_installed,
                                          form.car_folded_in_east_transfer,
                                          form.car_never_in_safety) }}
              </div>
          </div>
          <div class="col-sm-6">
              <div class="col-md-12">
                  {{ macros.render_fields("M08: Composting",
                                      form.compost_ejected_not_in_safety,
                                      form.compost_ejected_in_safety) }}

                  {{ macros.render_fields("M07: Cleanup",
                                          form.plastic_bags_in_safety,
                                          form.animals_in_circles_without_bags,
                                          form.chicken_in_small_landfill_circle) }}

                  {{ macros.render_fields("M10: Demolition", form.all_beams_not_in_setup_position) }}

                  {{ macros.render_fields("M01: Using Recycled Material",
                                          form.green_bins_in_opp_safety,
                                          form.opp_green_bins_in_safety) }}

                  {{ macros.render_fields("M09: Salvage", form.valuables_in_safety) }}

                  {{ macros.render_fields("M11: Purchasing Decisions", form.planes_in_safety) }}

                  {{ macros.render_fields("M12: Repurposing",
                                          form.compost_in_toy_package,
                                          form.package_in_original_condition) }}
              </div>
          </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center">
                {% if id!=None %}
                    {{ macros.render_submit(style_='padding-left: 23px', cancel_link=url_for('review'), delete_link=url_for('.delete', score_id=id)) }}
                {% elif repeat == true %}
                    {{ macros.render_submit(style_='padding-left: 23px', include_reset=true) }}
                {% else %}
                    {{ macros.render_submit(style_='padding-left: 23px', cancel_link=url_for('review')) }}
                {% endif %}
            </div>
        </div>
    {% endcall %}
{% endblock %}

app/templates/scoring/score_list.html
{% extends "layout.html" %}
{% import "scoring/_scoring_helpers.html" as macros %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/datatables.min.css') }}">
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/libs/datatables.min.js') }}"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $(".table").DataTable({
            scrollY:        '50vh',
            scrollCollapse: true,
            paging:         false
            });
        });
    </script>
{% endblock %}
{% block title %}FLL Qualifying Scores{% endblock %}
{% block pageContent %}
  <h3>Qualifying Scores</h3>
  <a href="{{ url_for('.add') }}">Add a new score</a>
  <table class="table table-hover display" width="100%">
    <thead>
      <tr>
        <th>Number</th>
        <th>Name</th>
        <th>Best</th>
        <th>Round 1</th>
        <th>Round 2</th>
        <th>Round 3</th>
      </tr>
    </thead>
    <tbody>
      {% for team in teams %}
        <tr>
          <td>{{ team.number }}</td>
          <td>{{ team.name }}</td>
          {% if team.best != None %}
            <td>
              <a href="{{ url_for('.edit', score_id=team.best.id) }}">{{ team.best.total }}</a>
            </td>
          {% else %}
            <td></td>
          {% endif %}
          <td>{{ macros.render_score(team, 1) }}</td>
          <td>{{ macros.render_score(team, 2) }}</td>
          <td>{{ macros.render_score(team, 3) }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
{% endblock %}