app/awards/views.py
from flask import Blueprint, render_template, flash, request, redirect, \
    url_for
from flask.ext.login import login_required
from app import db
from app.util import create_pdf, sortTeamsWithPlaceholder
from app.teams.models import Team
from models import AwardWinner, AwardCategory
from forms import AwardWinnerForm
from app.models import EventSettings

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_awards = Blueprint('awards', __name__, url_prefix='/awards')


# Restrict access to authorized users only
@mod_awards.before_request
@login_required
def before_request():
    pass


# Awards page
@mod_awards.route("/", methods=['GET'])
def index():
    teams = Team.query.all()

    if not teams:
        return render_template("no_teams.html")

    award_winners = AwardWinner.query.all()

    award_winners = sorted(award_winners, key=lambda x: x.friendly_award_name)
    for winner in award_winners:
        winner.category_name = AwardCategory(winner.category_id).friendly_name
    return render_template("awards/awards.html", award_winners=award_winners)


# Award winner report
@mod_awards.route("/awards_report.pdf")
def awards_pdf():
    award_winners = AwardWinner.query.all()
    title = EventSettings.query.first().name

    award_winners = sorted(award_winners, key=lambda x: x.friendly_award_name)
    for winner in award_winners:
        winner.category_name = AwardCategory(winner.category_id).friendly_name

    awards = render_template("awards/awards_report.html",
                             award_winners=award_winners,
                             title="Award Winners Report: %s" % title)

    pdf = create_pdf(awards, 'awards_report.pdf')
    return pdf


# Edit a previously-entered award winner
@mod_awards.route("/<int:award_winner_id>/assign", methods=['GET', 'POST'])
def assign_award_winner(award_winner_id):
    teams = Team.query.all()

    if not teams:
        return render_template("no_teams.html")

    award_winner = AwardWinner.query.get(award_winner_id)
    form = AwardWinnerForm(obj=award_winner)
    form.team_id.choices = [(t.id, t.number) for t in
                            sortTeamsWithPlaceholder(teams)]

    if request.method == 'POST' and form.validate_on_submit():
        form.populate_obj(award_winner)
        db.session.commit()
        return redirect(url_for(".index"))
    elif request.method == 'POST':
        flash('Failed validation', 'danger alert-auto-dismiss')
    return render_template("awards/award_winner_form.html", form=form, award=award_winner.friendly_award_name)


# Delete an award winner
@mod_awards.route("/<int:award_winner_id>/delete", methods=['GET', 'POST'])
def clear_award_winner(award_winner_id):
    award_winner = AwardWinner.query.get(award_winner_id)
    if request.method == 'POST':
        award_winner.team_id = None
        db.session.add(award_winner)
        db.session.commit()
        return redirect(url_for(".index"))
    return render_template("delete.html", identifier="award winner for %s"
                                                     % award_winner.friendly_award_name)


@mod_awards.route("/populate_slots", methods=['GET', 'POST'])
def populate_slots():
    if request.method == 'POST':
        # Remove any existing winners
        for existing_winner in AwardWinner.query.all():
            db.session.delete(existing_winner)
        db.session.commit()

        # Seed new slots
        slots = []
        is_championship = EventSettings.query.first().is_championship

        for category in AwardCategory:
            if is_championship or category == AwardCategory.Champions or category == AwardCategory.Robot_Performance:
                for i in range(0, 2):
                    slots.append(AwardWinner(category_id=category.value, place=i))
            else:
                slots.append(AwardWinner(category_id=category.value, place=0))

        for slot in slots:
            db.session.add(slot)
        db.session.commit()
        flash("Populated slots", 'success')
        return redirect(url_for(".index"))
    return render_template("awards/populate_slots.html")


# Sort teams by number
def by_team(team):
    return team.number

app/matches/views.py
import csv
import os
from flask import Blueprint, flash, render_template, request, redirect, \
    url_for
from flask.ext.login import login_required
from app import db
from app.models import EventSettings
from app.util import create_pdf
from models import Match, MatchSlot, CompetitionTable
from forms import UploadForm, AnnouncerDisplayForm
from app.teams.models import Team


mod_matches = Blueprint('matches', __name__, url_prefix='/matches')


# Match list
@mod_matches.route("/")
def index():
    matches = Match.query.all()
    competition_tables = CompetitionTable.query.all()
    return render_template("matches/match_list.html", matches=matches, competition_tables=competition_tables)


@mod_matches.route("/match_schedule.pdf")
def matches_pdf():
    matches = Match.query.all()
    competition_tables = CompetitionTable.query.all()
    title = EventSettings.query.first().name
    match_report = render_template("matches/match_report.html",
                                   matches=matches,
                                   competition_tables=competition_tables,
                                   title="Match Report: %s" % title)
    pdf = create_pdf(match_report, 'matches.pdf')
    return pdf


@mod_matches.route("/announcer", methods=['GET', 'POST'], defaults={'match_id': None})
@mod_matches.route("/announcer/<int:match_id>", methods=['GET', 'POST'])
def announcer_display(match_id):
    # TODO filter only on correct type once we have playoff matches
    matches = Match.query.all()
    
    form = AnnouncerDisplayForm()
    form.match_id.choices = [(m.id, m.number) for m in matches]
    
    match = None
    if match_id is None:
        match = matches[0]
    else:
        match = Match.query.filter_by(id=match_id).first()

    allow_previous = match.number != 1
    allow_next = match.number != len(matches)

    # set initial value for the match-jump drop-down
    form.match_id.data = match_id
    
    if request.method == 'POST' and request.form['end'] == 'jump':
        return redirect(url_for(".announcer_display", match_id = request.form['match_id']))
    elif request.method == 'POST' and request.form['end'] == 'previous':
        new_match = Match.query.filter_by(number = match.number - 1).first()
        return redirect(url_for(".announcer_display", match_id = new_match.id))
    elif request.method == 'POST' and request.form['end'] == 'next':
        new_match = Match.query.filter_by(number = match.number + 1).first()
        return redirect(url_for(".announcer_display", match_id = new_match.id))
    
    return render_template("matches/announcer_display.html",
                           form=form,
                           match=match,
                           allow_previous=allow_previous,
                           allow_next=allow_next)
    
@mod_matches.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    if request.method == 'POST' and 'file' in request.files:
        # define filename for the uploaded file
        filename = 'uploaded_teams.csv'

        # delete any existing copies of the uploaded file
        if os.path.isfile(filename):
            os.remove(filename)
            print 'removed file'

        # get the file from the POST data
        file = request.files['file']
        file.save(filename)

        
        # wipe all previous tables/ matches, with warning first
        for existing_slot in MatchSlot.query.all():
            db.session.delete(existing_slot)
        
        for existing_table in CompetitionTable.query.all():
            db.session.delete(existing_table)
        
        for existing_match in Match.query.all():
            db.session.delete(existing_match)
            
        db.session.commit()
        
        # extract data from file
        tables = addTablesFromCsv(filename)
        matchCount = addMatchesFromCsv(filename, tables)
        flash('Imported %d matches' % matchCount, 'success')

        os.remove(filename)
        return redirect(url_for(".index"))
    return render_template("matches/match_upload_form.html", form=form)


def addTablesFromCsv(filename):
    competition_tables = []

    with open(filename) as csvfile:
        reader = csv.DictReader(csvfile)

        i = 0
        fields = reader.fieldnames
        
        # Get the fields that start with 'Table' (may want to make this more flexible later on)
        table_names = filter(lambda k: 'Table' in k, fields)
        for table in table_names:
            comp_table = CompetitionTable(i, table)
            competition_tables.append(comp_table)
            db.session.add(comp_table)
            i += 1

        db.session.commit()
        return competition_tables


def addMatchesFromCsv(filename, tables):
    matches = []
    competition_tables = {}
    teams = {}

    # setup team and table dictionaries for quick access
    for team in Team.query.all():
        teams[team.number] = team.id

    for table in tables:
        competition_tables[table.name] = table.id

    with open(filename) as csvfile:
        reader = csv.DictReader(csvfile)

        j = 1
        for row in reader:
            # Create the overall match object
            match = Match(j, 'Q', row['Round'], row['Time'])
            
            j += 1
            for key, value in competition_tables.iteritems():
                # if there is a team number in the table column, then add a match-slot object
                if row[key]:
                    team_id = Team.query.filter_by(number = row[key]).first().id
                    table_id = value
                    match.slots.append(MatchSlot(table_id, team_id))

            matches.append(match)
            db.session.add(match)

        db.session.commit()

        return len(matches)

app/teams/views.py
import csv
import os
from flask import Blueprint, flash, render_template, request, redirect, \
    url_for
from flask.ext.login import login_required
from app import db
from app.util import create_pdf
from models import Team
from forms import TeamForm, UploadForm
from app.models import EventSettings


# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_teams = Blueprint('teams', __name__, url_prefix='/teams')


# Team list
@mod_teams.route("/")
def index():
    teams = Team.query.all()
    return render_template("teams/teams.html",
                           teams=sorted(teams, key=by_team))


# add a new team
@mod_teams.route("/new", methods=['GET', 'POST'])
@login_required
def add():
    form = TeamForm()
    if request.method == 'POST' and form.validate_on_submit():
        team = Team()
        form.populate_obj(team)
        db.session.add(team)
        db.session.commit()
        return redirect(url_for(".index"))
    elif request.method == 'POST':
        flash('Failed validation', 'danger alert-auto-dismiss')
    return render_template("teams/team_form.html", form=form, id=None)


# Upload teams via CSV file
@mod_teams.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    if request.method == 'POST' and 'file' in request.files:
        # define filename for the uploaded file
        filename = 'uploaded_teams.csv'

        # delete any existing copies of the uploaded file
        if os.path.isfile(filename):
            os.remove(filename)
            print 'removed file'

        # get the file from the POST data
        file = request.files['file']
        file.save(filename)

        # extract team data from file
        teams = extractTeamsFromCsv(filename)

        # add teams to database
        teamCount = 0
        for team in teams:
            # make sure team doesn't already exist first
            existing = Team.query.filter_by(number=team.number).first()
            if existing is None:
                db.session.add(team)
                teamCount = teamCount + 1
        if teamCount > 0:
            db.session.commit()

        flash('Imported %d teams' % teamCount, 'success')
        os.remove(filename)
        return redirect(url_for(".index"))
    return render_template("teams/team_upload_form.html", form=form)


def extractTeamsFromCsv(filename):
    teams = []
    with open(filename) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            team = Team(number=int(row['Number']),
                        name=row['Name'],
                        affiliation=row['Affiliation'],
                        city=row['City'],
                        state=row['State'],
                        is_rookie=row['Rookie'] == 'True')
            teams.append(team)
    return teams


# Edit a previously-entered team
@mod_teams.route("/<int:team_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(team_id):
    team = Team.query.get(team_id)
    form = TeamForm(obj=team)
    del form.number

    if request.method == 'POST' and form.validate_on_submit():
        form.populate_obj(team)
        db.session.commit()
        return redirect(url_for(".index"))
    elif request.method == 'POST':
        flash('Failed validation', 'danger alert-auto-dismiss')
    return render_template("teams/team_form.html", form=form, number=team.number, id=team.id)


# Delete a team
@mod_teams.route("/<int:team_id>/delete", methods=['GET', 'POST'])
@login_required
def delete(team_id):
    team = Team.query.get(team_id)
    if request.method == 'POST':
        # delete related scores
        for score in team.scores:
            db.session.delete(score)

        # delete related judging entries
        if team.presentation is not None:
            db.session.delete(team.presentation)
        if team.technical is not None:
            db.session.delete(team.technical)
        if team.core_values is not None:
            db.session.delete(team.core_values)

        # clear any assigned awards
        for award in team.awards:
            award.team_id = None

        # delete the team
        db.session.delete(team)
        db.session.commit()
        return redirect(url_for(".index"))
    return render_template("delete.html", identifier="team %d" % team.number)


# Team PDF report
@mod_teams.route('/teams_report.pdf')
def teams_pdf():
    teams = Team.query.all()
    title = EventSettings.query.first().name
    team_report = render_template("teams/team_report.html",
                                  teams=sorted(teams, key=by_team),
                                  title="Team Report: %s" % title)
    pdf = create_pdf(team_report, 'teams.pdf')
    return pdf


@mod_teams.route("/category_results.pdf", methods=['GET'])
@login_required
def category_results_pdf():
    teams = Team.query.all()
    title = EventSettings.query.first().name
    data = render_template("teams/category_results.html",
                           teams=sorted(teams, key=by_team),
                           title="Category Results Report: %s" % title)

    pdf = create_pdf(data, 'category_results.pdf')
    return pdf


# Sort teams by number
def by_team(team):
    return team.number

app/templates/_helpers.html
{# http://bear-z.com/python/render-bootstrap-3-forms-with-wtforms-and-jinja/ #}

{#
  render a field with errors
  only use as a call block
#}
{% macro render_with_errors(field, label_visible=true) %}
  <div class="form-group form-group-sm {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
    {% if (field.type != 'HiddenField' and field.type !='CSRFTokenField') and label_visible %}
      <label for="{{ field.id }}" class="control-label col-sm-6">{{ field.label.text }}</label>
    {% endif %}
    <div class="col-sm-6">
      {{ caller() }}
    </div>
    {% if field.errors %}
      {% for e in field.errors %}
        <p class="help-block">{{ e }}</p>
      {% endfor %}
    {% endif %}
  </div>
{%- endmacro %}

{% macro render_selector(field, label_size=6, selector_size=6) %}
  <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
    <label for="{{ field.id }}" class="control-label col-sm-{{label_size}}">{{ field.label.text }}</label>
    <div class="col-sm-{{selector_size}}">
      {{field(class="form-control", **kwargs)}}
      {% if field.errors %}
        {% for e in field.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{%- endmacro %}

{#
  Renders a standard field for bootstrap 3 standards.
  Params:
    field - WTForm field
    kwargs - pass any arguments you want in order to put them into the html attributes.
    There are few exceptions: for - for_, class - class_, class__ - class_

  Example usage:
    {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
#}
{% macro render_basic_field(field, label_visible=true) -%}
  {% call render_with_errors(field, label_visible) %}
    {% if field.type == 'FileField' %}
      {{field(**kwargs)}}
    {% else %}
      {{field(class="form-control", **kwargs)}}
    {% endif %}
  {%- endcall %}
{%- endmacro %}

{#
  Renders radio field as a button group
  Params:
    field - WTForm field (there are no check, but you should put here only BooleanField.
    kwargs - pass any arguments you want in order to put them into the html attributes.
    There are few exceptions: for - for_, class - class_, class__ - class_
  Example usage:
    {{ macros.render_radio_field(form.answers) }}
 #}
{% macro render_radio_field(field, label_visible=true) -%}
  {% call render_with_errors(field, label_visible) %}
    <div class="btn-group" data-toggle="buttons">
    {% for value, label, _ in field.iter_choices() %}
      {% if field.data == value %}
        <label class="btn btn-default btn-selector active">
          <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}" checked="checked">{{ label }}
        </label>
      {% else %}
        <label class="btn btn-default btn-selector">
          <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
        </label>
      {% endif %}
    {% endfor %}
    </div>
  {%- endcall %}
{%- endmacro %}

{#
  Renders a checkbox field
#}
{% macro render_checkbox_field(field) -%}
 {% call render_with_errors(field) %}
    <div class="checkbox">
      <label>
        {{ field(type='checkbox', **kwargs) }}
      </label>
    </div>
  {%- endcall %}
{%- endmacro %}

{#
  Render a submit field
#}
{% macro render_submit(action_text='Submit', btn_class='btn btn-primary', cancel_link=None, delete_link=None, include_reset=false) -%}
  <div class="form-group">
    <div style="{{ kwargs.pop('style_', '') }}">
      <button type="submit" class="{{ btn_class }}" value="submit" name="end">{{ action_text }}</button>
      {% if include_reset %}
        <button type="submit" class="btn btn-default" value="reset" name="end">Reset</button>
      {% endif %}
      {% if cancel_link!=None %}
        <a href="{{ cancel_link }}" class="btn btn-default">Cancel</a>
      {% endif %}
      {% if delete_link!=None %}
        <a href="{{ delete_link }}" class="btn btn-danger"><i class="fa fa-trash-o fa-lg"></i> Delete</a>
      {% endif %}
    </div>
  </div>
{%- endmacro %}

{#
  Render a field using Bootstrap 3 standards
#}
{% macro render_field(field) -%}
  <div>
    {% if field.type == 'BooleanField' %}
      {{ render_checkbox_field(field) }}
    {% elif field.type == 'RadioField' %}
      {{ render_radio_field(field) }}
    {% else %}
      {{ render_basic_field(field) }}
    {% endif %}
  </div>
{%- endmacro %}

{#
  Render multiple fields inside a Bootstrap panel
#}
{% macro render_fields(title) %}
  <div>
      {% for f in varargs %}
        {{ render_field(f) }}
      {% endfor %}
  </div>
{%- endmacro %}

{#
  Renders WTForm in bootstrap way. There are two ways to call function:
  - as macros: it will render all field forms using cycle to iterate over them
  - as call: it will insert form fields as you specify:
  e.g.
    {% call macros.render_form(form, action_url=url_for('login_view'), action_text='Login'
                               class_='login-form') %}
      {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
      {{ macros.render_field(form.password, placeholder='Input password', type='password') }}
      {{ macros.render_checkbox_field(form.remember_me, type='checkbox') }}
    {% endcall %}

  Params:
    form - WTForm class
    action_url - url where to submit this form
    action_text - text of submit button
    class_ - sets a class for form
#}
{% macro render_form(form, action_url='', action_text='Submit', class_='', btn_class='btn btn-default', enctype="application/x-www-form-urlencoded", include_submit=true) -%}
  <form method="POST" action="{{ action_url }}" role="form" class="form {{ class_ }} form-horizontal" enctype="{{ enctype }}">
    {{ form.csrf_token }}
    {% if caller %}
      {{ caller() }}
    {% else %}
      <div class="row">
        <div class="col-sm-8 col-sm-offset-1">
          {% for f in form %}
            {{ render_field(f) }}
          {% endfor %}
        </div>
      </div>
    {% endif %}
    {% if include_submit %}
      <div class="row">
        <div class="col-sm-12 text-center">
          {{ render_submit(action_text, btn_class) }}
        </div>
      </div>
    {% endif %}
  </form>
{%- endmacro %}

app/templates/basic_form.html
{% extends "layout.html" %}
{% import "_helpers.html" as macros %}
{% block title %}{{title}}{% endblock %}
{% block pageContent %}
  <h1>{{title}}</h1>
  {{ macros.render_form(form, class_="{{form_id}}") }}
{% endblock %}

app/templates/change_password.html
{% extends "layout.html" %}
{% import "_helpers.html" as macros %}
{% block title %}Change Password{% endblock %}
{% block pageContent %}
  <h3>Change Password</h3>
  {{ macros.render_form(form, action_url="", action_text="Save", class_="change_password_form") }}
{% endblock %}

app/templates/delete.html
{% extends "layout.html" %}
{% block title %}Delete{% endblock %}
{% block pageContent %}
<script type="text/javascript">
  // TODO Move this to a global JS file
  function goBack() {
    window.history.back();
  }
</script>
  <p>Really delete {{ identifier }}?<p>
  <form action="" method="post">
    <p><button class="btn" onclick="goBack()">Cancel</button>  <input type="submit" class="btn btn-danger" value="Delete"></p>
  </form>
{% endblock %}

app/templates/form_layout.html
{% extends "layout.html" %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/forms.js') }}"></script>
{% endblock %}

app/templates/layout.html
<!doctype html>
<html>
  <head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block styles %}
    {% endblock %}

    <script type="text/javascript" src="{{ url_for('static', filename='js/libs/jquery-1.11.3.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
    {% block scripts %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">FLL EvM</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('scoring.add', repeat=true) }}"><span class="fa fa-calculator"></span> Scoring</a></li>
            <li><a href="{{ url_for('review') }}"><span class="fa fa-edit"></span> Review</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-tachometer"></span> Other <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('teams.index') }}"><span class="fa fa-users"></span> Teams</a></li>
                <li><a href="{{ url_for('matches.index') }}"><span class="fa fa-calendar"></span> Matches</a></li>
                <li><a href="{{ url_for('awards.index') }}"><span class="fa fa-trophy"></span> Awards</a></li>
                <li><a href="{{ url_for('scoring.playoffs') }}"><span class="fa fa-flag"></span> Playoffs</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-file-pdf-o"></span> Reports<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('teams.teams_pdf') }}" target="blanks">Team List</a></li>
                <li><a href="{{ url_for('matches.matches_pdf') }}" target="blanks">Match Schedule</a></li>
                <li><a href="{{ url_for('scoring.ranks_pdf') }}" target="blanks">Robot Performance Rankings</a></li>
                <li><a href="{{ url_for('awards.awards_pdf') }}" target="blanks">Awards</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-desktop"></span> Displays<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('pit_display') }}" target="blank"><span class="fa fa-sort-numeric-asc"></span> Pit Display</a></li>
                <li><a href="{{ url_for('matches.announcer_display') }}"><span class="fa fa-microphone"></span> Announcer Display</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('settings') }}"><span class="fa fa-cog"></span> Settings</a></li>
            {% if current_user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-user"></span> {{ current_user.username }}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('change_password') }}"><span class="fa fa-pencil"></span> Change password</a></li>
                  <li><a href="{{ url_for('logout') }}"><span class="fa fa-sign-out"></span> Sign Out</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{{ url_for('login') }}"><span class="fa fa-sign-in"></span> Sign In</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <main id="content" role="main" class="container" style="padding-top: 70px;">

      <!--Display messages-->
      <!--https://gist.github.com/vicow/fc16173c356b79f951d2-->
      {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
        {% if messages %}
          {% for category, message in messages %}
            <div class="row col-sm-11 alert alert-{{ category }} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <!-- <strong>Title</strong> --> {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <!--Main block-->
      {% block pageContent %}
      {% endblock %}

    </main>
    <br>

    <!--Footer-->
    <div id="footer" class="container">
      {% block footer %}
      <small>&copy; Copyright 2016 by Ryan Foley</small>
      {% endblock %}
    </div>
  </body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% import "_helpers.html" as macros %}
{% block title %}Login{% endblock %}
{% block pageContent %}
  <h3>Login</h3>
  {{ macros.render_form(form, action_url="", action_text="Login", class_="login_form") }}
{% endblock %}

app/templates/no_teams.html
{% extends "layout.html" %}
{% block title %}FLL EM{% endblock %}
{% block pageContent %}
<h1>No Teams</h1>
<br />
<p>Please <a href="{{ url_for('teams.index') }}">add teams</a> before trying to enter scoring, judging, or awards data</p>
{% endblock %}

app/templates/settings.html
{% extends "layout.html" %}
{% import "_helpers.html" as macros %}
{% block title %}FLL System Settings{% endblock %}
{% block pageContent %}
  <h1>Settings</h1>
  {{ macros.render_form(form, action_url="", action_text="Save", class_="event_settings_form") }}
{% endblock %}